### ISSUE TITLE
How to toggle the dark mode?

### ISSUE THREAD

**Issue by yanganto** [1j01/simple-console#3]
I can find the option to toggle the dark mode in README file. Thank you.

**Comment by 1j01** [comment]
The dark styles take effect when the console element or a parent contains the class `dark`.

You could add a theme switcher like so:

```js
var button = console.addButton(function() {
    if (console.element.classList.contains("dark")) {
        console.element.classList.remove("dark");
    } else {
        console.element.classList.add("dark");
    }
});
button.textContent = "◐";
button.setAttribute("title", "Toggle dark theme");
button.setAttribute("aria-label", "Toggle dark theme");
```

**Comment by 1j01** [comment]
Restructured the README to make it easier to find https://github.com/1j01/simple-console/commit/871d9fa93f9bccf88891f2b06300551709c64242
